"""core schema

Revision ID: ef62fe967e03
Revises: 
Create Date: 2026-10-05 13:19:10.436919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef62fe967e03'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('registration_country', sa.String(length=2), nullable=True),
    sa.Column('legal_identifiers', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('business_categories', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('service_regions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('currencies', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('company_size', sa.String(length=50), nullable=True),
    sa.Column('min_opportunity_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('max_opportunity_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('tender_preferences', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('profile_completeness', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.Enum('government_portal', 'government_department', 'private_corporate', 'supplier_portal', 'newspaper', 'email', 'upload', name='sourcetype', native_enum=False, length=40), nullable=False),
    sa.Column('access_method', sa.String(length=100), nullable=True),
    sa.Column('base_url', sa.String(length=1000), nullable=True),
    sa.Column('refresh_schedule', sa.String(length=100), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('health', sa.Enum('unknown', 'healthy', 'degraded', 'failing', name='sourcehealth', native_enum=False, length=40), nullable=False),
    sa.Column('coverage_notes', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_platform_admin', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_events',
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('object_type', sa.String(length=100), nullable=False),
    sa.Column('object_id', sa.String(length=64), nullable=False),
    sa.Column('before', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('after', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_object_id'), 'audit_events', ['object_id'], unique=False)
    op.create_index(op.f('ix_audit_events_object_type'), 'audit_events', ['object_type'], unique=False)
    op.create_index(op.f('ix_audit_events_organization_id'), 'audit_events', ['organization_id'], unique=False)
    op.create_table('evidence',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('doc_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('supersedes_id', sa.Uuid(), nullable=True),
    sa.Column('issuer', sa.String(length=255), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('issued_on', sa.Date(), nullable=True),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.Column('jurisdiction', sa.String(length=100), nullable=True),
    sa.Column('confidentiality', sa.String(length=50), nullable=True),
    sa.Column('approval_state', sa.Enum('draft', 'pending', 'approved', 'rejected', name='approvalstate', native_enum=False, length=40), nullable=False),
    sa.Column('storage_key', sa.String(length=1000), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supersedes_id'], ['evidence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_organization_id'), 'evidence', ['organization_id'], unique=False)
    op.create_table('memberships',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('owner_admin', 'bid_manager', 'business_development', 'technical_contributor', 'finance_contributor', 'compliance_reviewer', 'approver', 'viewer', name='role', native_enum=False, length=40), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'user_id')
    )
    op.create_index(op.f('ix_memberships_organization_id'), 'memberships', ['organization_id'], unique=False)
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.create_table('tenders',
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('uploaded_by_id', sa.Uuid(), nullable=True),
    sa.Column('buyer_name', sa.String(length=255), nullable=True),
    sa.Column('reference_number', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('procurement_type', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('lifecycle_status', sa.Enum('unknown', 'open', 'amended', 'closed', 'cancelled', 'awarded', name='tenderlifecycle', native_enum=False, length=40), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline_timezone', sa.String(length=64), nullable=True),
    sa.Column('estimated_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('original_url', sa.String(length=2000), nullable=True),
    sa.Column('first_retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.Column('unresolved_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('verification_status', sa.Enum('needs_verification', 'verified', name='verificationstatus', native_enum=False, length=40), nullable=False),
    sa.Column('dedup_key', sa.String(length=255), nullable=True),
    sa.Column('deadline_history', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tenders_buyer_reference', 'tenders', ['buyer_name', 'reference_number'], unique=False)
    op.create_index(op.f('ix_tenders_dedup_key'), 'tenders', ['dedup_key'], unique=False)
    op.create_index(op.f('ix_tenders_organization_id'), 'tenders', ['organization_id'], unique=False)
    op.create_index(op.f('ix_tenders_source_id'), 'tenders', ['source_id'], unique=False)
    op.create_table('bids',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('tender_id', sa.Uuid(), nullable=False),
    sa.Column('stage', sa.Enum('discovered', 'shortlisted', 'evaluating', 'participation_approved', 'preparing', 'internal_review', 'approved_to_submit', 'submitted', 'under_evaluation', 'awarded', 'lost', 'withdrawn', 'cancelled', name='bidstage', native_enum=False, length=40), nullable=False),
    sa.Column('decision', sa.Enum('bid', 'no_bid', 'hold', name='biddecision', native_enum=False, length=40), nullable=True),
    sa.Column('decision_rationale', sa.Text(), nullable=True),
    sa.Column('decided_by_id', sa.Uuid(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_review_date', sa.Date(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('internal_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expected_bid_cost', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('potential_contract_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'tender_id')
    )
    op.create_index(op.f('ix_bids_organization_id'), 'bids', ['organization_id'], unique=False)
    op.create_index(op.f('ix_bids_tender_id'), 'bids', ['tender_id'], unique=False)
    op.create_table('lots',
    sa.Column('tender_id', sa.Uuid(), nullable=False),
    sa.Column('lot_number', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('estimated_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tender_id', 'lot_number')
    )
    op.create_index(op.f('ix_lots_tender_id'), 'lots', ['tender_id'], unique=False)
    op.create_table('tender_versions',
    sa.Column('tender_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('document_hash', sa.String(length=128), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=True),
    sa.Column('storage_key', sa.String(length=1000), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('superseded_by_id', sa.Uuid(), nullable=True),
    sa.Column('change_summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['tender_versions.id'], ),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tender_id', 'document_hash')
    )
    op.create_index(op.f('ix_tender_versions_tender_id'), 'tender_versions', ['tender_id'], unique=False)
    op.create_table('bid_lots',
    sa.Column('bid_id', sa.Uuid(), nullable=False),
    sa.Column('lot_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['bid_id'], ['bids.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.PrimaryKeyConstraint('bid_id', 'lot_id')
    )
    op.create_table('requirements',
    sa.Column('tender_id', sa.Uuid(), nullable=False),
    sa.Column('lot_id', sa.Uuid(), nullable=True),
    sa.Column('tender_version_id', sa.Uuid(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('kind', sa.Enum('mandatory', 'scored', name='requirementkind', native_enum=False, length=40), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('citation', sa.String(length=500), nullable=True),
    sa.Column('origin', sa.Enum('extracted', 'manual', name='requirementorigin', native_enum=False, length=40), nullable=False),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.ForeignKeyConstraint(['tender_version_id'], ['tender_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requirements_tender_id'), 'requirements', ['tender_id'], unique=False)
    op.create_table('tasks',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('bid_id', sa.Uuid(), nullable=True),
    sa.Column('task_type', sa.Enum('registration', 'tender_document_purchase', 'pre_bid_attendance', 'site_visit', 'clarification_submission', 'bid_security', 'physical_delivery', 'other', name='tasktype', native_enum=False, length=40), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('todo', 'in_progress', 'blocked', 'done', name='taskstatus', native_enum=False, length=40), nullable=False),
    sa.Column('assignee_id', sa.Uuid(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['bid_id'], ['bids.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_bid_id'), 'tasks', ['bid_id'], unique=False)
    op.create_index(op.f('ix_tasks_organization_id'), 'tasks', ['organization_id'], unique=False)
    op.create_table('requirement_assessments',
    sa.Column('requirement_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('bid_id', sa.Uuid(), nullable=True),
    sa.Column('ai_status', sa.Enum('unreviewed', 'meets_requirement', 'partially_meets', 'does_not_meet', 'missing_evidence', 'needs_interpretation', 'not_applicable', name='compliancestatus', native_enum=False, length=40), nullable=True),
    sa.Column('reviewer_status', sa.Enum('unreviewed', 'meets_requirement', 'partially_meets', 'does_not_meet', 'missing_evidence', 'needs_interpretation', 'not_applicable', name='compliancestatus', native_enum=False, length=40), nullable=False),
    sa.Column('evidence_id', sa.Uuid(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('not_applicable_justification', sa.Text(), nullable=True),
    sa.Column('reviewed_by_id', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bid_id'], ['bids.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requirement_id', 'organization_id')
    )
    op.create_index(op.f('ix_requirement_assessments_organization_id'), 'requirement_assessments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_requirement_assessments_requirement_id'), 'requirement_assessments', ['requirement_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_requirement_assessments_requirement_id'), table_name='requirement_assessments')
    op.drop_index(op.f('ix_requirement_assessments_organization_id'), table_name='requirement_assessments')
    op.drop_table('requirement_assessments')
    op.drop_index(op.f('ix_tasks_organization_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_bid_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_requirements_tender_id'), table_name='requirements')
    op.drop_table('requirements')
    op.drop_table('bid_lots')
    op.drop_index(op.f('ix_tender_versions_tender_id'), table_name='tender_versions')
    op.drop_table('tender_versions')
    op.drop_index(op.f('ix_lots_tender_id'), table_name='lots')
    op.drop_table('lots')
    op.drop_index(op.f('ix_bids_tender_id'), table_name='bids')
    op.drop_index(op.f('ix_bids_organization_id'), table_name='bids')
    op.drop_table('bids')
    op.drop_index(op.f('ix_tenders_source_id'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_organization_id'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_dedup_key'), table_name='tenders')
    op.drop_index('ix_tenders_buyer_reference', table_name='tenders')
    op.drop_table('tenders')
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_organization_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_evidence_organization_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_audit_events_organization_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_object_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_object_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('sources')
    op.drop_table('organizations')
    # ### end Alembic commands ###
